version: '2.4'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123share
      POSTGRES_USER: postgres
      POSTGRES_DB: pay_share
      PGDATA: /var/lib/postgresql/data/pgdata

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5